version: "3.9"  # optional since v1.27.0
services:
  shine_api_gateway:
    container_name: shine_api_gateway
    image: nginx
    restart: always
    ports:
      - "80:8502"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Logs:/shineapiserver/Logs
    depends_on:
      - shine_api_server
  shine_api_server:
    container_name: shine_api_server
    build:
      context: .
      dockerfile: Dockerfile-api-server
    restart: always
    ports:
      - "8500:8500"
    volumes:
      - logvolume:/var/log
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongodb:27017
    depends_on:
      - mongodb
  shine_websocket_server:
    container_name: shine_websocket_server
    build:
      context: .
      dockerfile: Dockerfile-websocker-server
    restart: always
    ports:
      - "8501"
    env_file:
      - .env
  shine_email_server:
    container_name: shine_email_server
    build:
      context: .
      dockerfile: Dockerfile-email-server
    restart: always
    env_file:
      - .env
    depends_on:
      shine_websocket_server:
        condition: service_started
      shine_api_gateway:
        condition: service_started
  shine_logflusher_server:
    container_name: shine_logflusher_server
    build:
      context: .
      dockerfile: Dockerfile-logflusher-server
    restart: always
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongodb:27017,  shine_api_server:8500, shine_websocket_server:8501
    depends_on:
      - shine_api_gateway
      - shine_api_server
      - shine_websocket_server
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  shine_logger_client:
    container_name: shine_logger_client
    build:
      context: ../../shineloggerclient/
      dockerfile: Dockerfile-development
    restart: always
    volumes:
      - logvolume:/var/log
      - ../../shineloggerclient/:/app
    ports:
      - "3000:3000"
    environment:
      WAIT_HOSTS: shine_api_server:8500
    depends_on:
      - shine_api_server
volumes:
  logvolume: {}