FROM denoland/deno:alpine-1.24.3


WORKDIR /shineapiserver/Shared

# Cache the dependencies as a layer (the following two steps are re-run only when deps.ts is modified).
# Ideally cache deps.ts will download and compile _all_ external files used in main.ts.
COPY Shared/deps.ts .

COPY Shared/constants.ts .

COPY Shared/cipher.ts .


RUN deno cache deps.ts


WORKDIR /shineapiserver/ShineApiServer

# These steps will be re-run upon each file change in your working directory:
ADD ShineApiServer .
# Compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno cache server.ts

CMD ["run", "--allow-net","--allow-env","--allow-read","--allow-write", "server.ts"]