FROM node:alpine as builder

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x /wait

WORKDIR /app

COPY package.json .

COPY yarn.lock .

RUN yarn install

COPY . .

ENV NODE_ENV dev

EXPOSE 3000

CMD yarn run dev

